alter sequence aportacion_seq increment by 1;
alter sequence caja_seq increment by 1;
alter sequence clase_seq increment by 1;
alter sequence destinatario_seq increment by 1;
alter sequence tipo_alimento_seq increment by 1;


INSERT INTO destinatario(direccion, nombre, persona_contacto, telefono, id) VALUES ('C/ Jaén nº 24', 'Parroquia San Pedro', 'Don Jose Luis', '678 489 282', NEXTVAL('destinatario_seq'));
INSERT INTO destinatario(direccion, nombre, persona_contacto, telefono, id) VALUES ('C/ Rosario nº 78', 'Comedor social San Juan de Dios', 'Francisco Gomez', '956 783 211', NEXTVAL('destinatario_seq'));
INSERT INTO destinatario(direccion, nombre, persona_contacto, telefono, id) VALUES ('C/ Betis nº 196', 'Caritas', 'Sara Fernández', '656 467 629', NEXTVAL('destinatario_seq'));
INSERT INTO destinatario(direccion, nombre, persona_contacto, telefono, id) VALUES ('C/ López de gomara nº 56, bloque 2, 4ºA', 'Banco de alimentos', 'Mario Marquez', '756 472 987', NEXTVAL('destinatario_seq'));
INSERT INTO destinatario(direccion, nombre, persona_contacto, telefono, id) VALUES ('C/ Esperanza de triana nº 34', 'Plataforma del voluntariado social', 'Ignacio Franco', '676 439 675', NEXTVAL('destinatario_seq'));
INSERT INTO clase(nombre, tutor, id) VALUES ('2 DAM' ,'Luis Miguel López' ,NEXTVAL('clase_seq'));
INSERT INTO clase(nombre, tutor, id) VALUES ('1 DAM' ,'Miguel Campos' ,NEXTVAL('clase_seq'));
INSERT INTO clase(nombre, tutor, id) VALUES ('1 FPB' ,'Julio Vera' ,NEXTVAL('clase_seq'));
INSERT INTO clase(nombre, tutor, id) VALUES ('1 COMERCIO' ,'Mónica Naranjo' ,NEXTVAL('clase_seq'));
INSERT INTO clase(nombre, tutor, id) VALUES ('2 AYF' ,'Paco Pepe' ,NEXTVAL('clase_seq'));
INSERT INTO tipo_alimento(nombre, id) VALUES ('Pasta', NEXTVAL('tipo_alimento_seq'));
INSERT INTO tipo_alimento(nombre, id) VALUES ('Dulces', NEXTVAL('tipo_alimento_seq'));
INSERT INTO tipo_alimento(nombre, id) VALUES ('Legumbres', NEXTVAL('tipo_alimento_seq'));
INSERT INTO tipo_alimento(nombre, id) VALUES ('Arroz', NEXTVAL('tipo_alimento_seq'));
INSERT INTO tipo_alimento(nombre, id) VALUES ('Leche', NEXTVAL('tipo_alimento_seq'));
INSERT INTO tipo_alimento(nombre, id) VALUES ('Huevos', NEXTVAL('tipo_alimento_seq'));
INSERT INTO tipo_alimento(nombre, id) VALUES ('Carne', NEXTVAL('tipo_alimento_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (1, '2022-12-13', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (1, '2022-12-16', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (2, '2022-12-17', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (2, '2022-12-12', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (2, '2022-12-17', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (3, '2022-12-18', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (4, '2022-12-19', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (4, '2022-12-21', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (4, '2022-12-23', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (4, '2022-12-20', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (5, '2022-12-18', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (2, '2022-12-16', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (5, '2022-12-16', NEXTVAL('aportacion_seq'));
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (8, 1, 1, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (5.7, 6, 1, 2);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (4, 4, 1, 3);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (10, 2, 2, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (8.2, 1, 3, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (4.6, 2, 3, 2);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (7, 7, 4, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (5.8, 7, 4, 2);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (7.2, 1, 4, 3);
--INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (6, 2, 4, 1);
--INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (14, 3, 4, 2);
--INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (12.5, 3, 4, 3);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (9, 5, 4, 4);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (10.3, 2, 5, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (12, 1, 6, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (17.2, 4, 7, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (9, 6, 7, 2);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (8, 2, 7, 3);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (7.6, 1, 8, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (8.7, 3, 9, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (2.8, 7, 9, 2);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (11, 5, 10, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (6.4, 5, 11, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (16, 4, 11, 2);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (7.9, 6, 12, 1);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 1), 1);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 2), 2);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 3), 3);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 4), 4);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 5), 5);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 6), 6);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 7), 7);
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (1, 0, 1, NEXTVAL('caja_seq'));
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (2, 0, 2, NEXTVAL('caja_seq'));
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (3, 0, 3, NEXTVAL('caja_seq'));
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (4, 0, 4, NEXTVAL('caja_seq'));
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (1, 0, 5, NEXTVAL('caja_seq'));
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (1, 0, 6, NEXTVAL('caja_seq'));
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (3, 0, 7, NEXTVAL('caja_seq'));
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (4, 0, 8, NEXTVAL('caja_seq'));
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (6, 1, 1);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (8, 1, 2);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (12, 2, 1);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (20, 3, 3);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (8, 4, 1);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (11, 5, 5);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (15, 6, 3);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (16, 7, 4);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (7, 4, 4);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (10, 8, 7);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (7, 4, 6);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (5, 8, 2);
UPDATE caja c SET kilos_totales = (SELECT SUM(cantidad_kgs) FROM tiene t WHERE t.caja_id = c.id);
UPDATE kilos_disponibles k SET cantidad_disponible = cantidad_disponible - (SELECT SUM(cantidad_kgs) FROM tiene t WHERE t.tipo_alimento_id = k.tipo_alimento);
UPDATE caja c SET qr = CONCAT('http://localhost:8080/caja/', c.id);