DELETE FROM detalle_aportacion;
DELETE FROM kilos_disponibles;

INSERT INTO  clase(nombre, tutor, id) VALUES ('2 DAM' ,'Luis Miguel López' ,NEXTVAL('clase_seq'));
INSERT INTO  clase(nombre, tutor, id) VALUES ('1 DAM' ,'Miguel Campos' ,NEXTVAL('clase_seq'));
INSERT INTO  clase(nombre, tutor, id) VALUES ('1 FPB' ,'Julio Vera' ,NEXTVAL('clase_seq'));
INSERT INTO  clase(nombre, tutor, id) VALUES ('1 COMERCIO' ,'Mónica Naranjo' ,NEXTVAL('clase_seq'));
INSERT INTO  clase(nombre, tutor, id) VALUES ('2 AYF' ,'Paco Pepe' ,NEXTVAL('clase_seq'));
INSERT INTO  tipo_alimento(nombre, id) VALUES ('Pasta', NEXTVAL('tipo_alimento_seq'));
INSERT INTO  tipo_alimento(nombre, id) VALUES ('Dulces', NEXTVAL('tipo_alimento_seq'));
INSERT INTO  tipo_alimento(nombre, id) VALUES ('Legumbres', NEXTVAL('tipo_alimento_seq'));
INSERT INTO  tipo_alimento(nombre, id) VALUES ('Arroz', NEXTVAL('tipo_alimento_seq'));
INSERT INTO  tipo_alimento(nombre, id) VALUES ('Leche', NEXTVAL('tipo_alimento_seq'));
INSERT INTO  tipo_alimento(nombre, id) VALUES ('Huevos', NEXTVAL('tipo_alimento_seq'));
INSERT INTO  tipo_alimento(nombre, id) VALUES ('Carne', NEXTVAL('tipo_alimento_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (1, '2022-12-13', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (1, '2022-12-16', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (2, '2022-12-17', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (2, '2022-12-12', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (2, '2022-12-17', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (3, '2022-12-18', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (4, '2022-12-19', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (4, '2022-12-21', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (4, '2022-12-23', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (4, '2022-12-20', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (5, '2022-12-18', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (2, '2022-12-16', NEXTVAL('aportacion_seq'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (5, '2022-12-16', NEXTVAL('aportacion_seq'));
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (8, 1, 1, 1);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (5.7, 6, 1, 2);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (4, 4, 1, 3);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (10, 2, 2, 1);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (8.2, 1, 3, 1);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (4.6, 2, 3, 2);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (7, 7, 4, 1);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (5.8, 7, 4, 2);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (7.2, 1, 4, 3);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (9, 5, 4, 4);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (10.3, 2, 5, 1);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (12, 1, 6, 1);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (17.2, 4, 7, 1);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (9, 6, 7, 2);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (8, 2, 7, 3);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (7.6, 1, 8, 1);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (8.7, 3, 9, 1);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (2.8, 7, 9, 2);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (11, 5, 10, 1);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (6.4, 5, 11, 1);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (16, 4, 11, 2);
INSERT INTO  detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (7.9, 6, 12, 1);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 1), 1);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 2), 2);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 3), 3);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 4), 4);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 5), 5);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 6), 6);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 7), 7);